server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/printify
    username: samuel
    password: helloworld

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
